In [35]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [36]:
data = {
    "SH" : [1,2,2,3,3,4,5,5,6,7,7,8,8,9,10],
    "ATT" : [55,60,6,62,70,72,75,80,78,82,85,88,90,92,95],
    "ASS_SCR" :[40,45,50,48,55,58,62,67,65,70,74,78,80,85,90],
    "STU_ID" : [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115],
    "Fi_Ma" : [35,40,43,45,50,54,60,64,66,71,74,79,82,87,92]
}

df = pd.DataFrame(data)

df

    SH  ATT  ASS_SCR  STU_ID  Fi_Ma
0    1   55       40     101     35
1    2   60       45     102     40
2    2    6       50     103     43
3    3   62       48     104     45
4    3   70       55     105     50
5    4   72       58     106     54
6    5   75       62     107     60
7    5   80       67     108     64
8    6   78       65     109     66
9    7   82       70     110     71
10   7   85       74     111     74
11   8   88       78     112     79
12   8   90       80     113     82
13   9   92       85     114     87
14  10   95       90     115     92

In [37]:
x = df[
    [
        "SH",
        "ATT",
        "ASS_SCR",
        "STU_ID"
    ]
]
y  = df ["Fi_Ma"]
x

    SH  ATT  ASS_SCR  STU_ID
0    1   55       40     101
1    2   60       45     102
2    2    6       50     103
3    3   62       48     104
4    3   70       55     105
5    4   72       58     106
6    5   75       62     107
7    5   80       67     108
8    6   78       65     109
9    7   82       70     110
10   7   85       74     111
11   8   88       78     112
12   8   90       80     113
13   9   92       85     114
14  10   95       90     115

In [38]:
y

0     35
1     40
2     43
3     45
4     50
5     54
6     60
7     64
8     66
9     71
10    74
11    79
12    82
13    87
14    92
Name: Fi_Ma, dtype: int64

In [39]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

In [40]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

OLR

In [41]:
model = LinearRegression()
model.fit(x, y)
print("Intercept: ", model.intercept_)

Intercept:  -129.27024012943542

In [42]:
coefficient_table = pd.DataFrame({
    "Feature" : x.columns,
    "Coefficient" : model.coef_
})

print(coefficient_table)

   Feature  Coefficient
0       SH     1.541476
1      ATT     0.010962
2  ASS_SCR     0.475681
3   STU_ID     1.410990

In [44]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score: ", r2)

MAE: 0.3396688546846889
MSE: 0.18958080542683478
RMSE: 0.4354087796850619
R2 Score:  0.9994823339657641

Ridge

In [45]:
model = make_pipeline(
    StandardScaler(),
    Ridge(alpha=1.0)
)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_pred)

from sklearn.linear_model import RidgeCV

model = RidgeCV(
    alphas= [0.01, 0.1, 1, 10,100],
    cv = 5
)

model.fit(x_train, y_train)

print("Best Alphas: ", model.alpha_)

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

print("\nMAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score: ", r2)

coefficient_table = pd.DataFrame({
    "Feature" : x.columns,
    "Coefficient" : model.coef_
})

print("\n",coefficient_table)

[71.06386161 78.89733293 35.30556047]
Best Alphas:  1.0

MAE: 0.15736304795041178
MSE: 0.03599534377712476
RMSE: 0.18972438898867156
R2 Score:  0.999901711743327

    Feature  Coefficient
0       SH     1.132307
1      ATT     0.016355
2  ASS_SCR     0.603667
3   STU_ID     1.227705

In [46]:
from sklearn.linear_model import RidgeCV

model = RidgeCV(
    alphas= [0.01, 0.1,10,100],
    cv = 5,
)

model.fit(x_train, y_train)

print("Best Alphas: ", model.alpha_)

y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

print("\nMAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score: ", r2)


coefficient_table = pd.DataFrame({
    "Feature" : x.columns,
    "Coefficient" : model.coef_
})

print("\n",coefficient_table)

Best Alphas:  0.1

MAE: 0.38713605246593374
MSE: 0.24911688229010184
RMSE: 0.49911610101268206
R2 Score:  0.9993197657947176

    Feature  Coefficient
0       SH     1.489198
1      ATT     0.009709
2  ASS_SCR     0.504485
3   STU_ID     1.373094

Lasso

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = make_pipeline(
    StandardScaler(),
    Lasso(alpha=0.1)
)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

lasso_model = model.named_steps["lasso"]

coefficient_table = pd.DataFrame({
    "Predicitor" : x.columns,
    "Lasso Coefficient" : lasso_model.coef_
})

print(coefficient_table)

  Predicitor  Lasso Coefficient
0         SH           4.074742
1        ATT           0.133936
2    ASS_SCR           6.849160
3     STU_ID           5.805057

In [48]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score: ", r2)

MAE: 0.3104981980822856
MSE: 0.16697027837423398
RMSE: 0.408619968154071
R2 Score:  0.9995440738757985

In [49]:
from sklearn.linear_model import LassoCV

model = make_pipeline(
    StandardScaler(),
    LassoCV(
        alphas=[0.001,0.1,1,10,100],
        cv = 5,
        max_iter=10000
    )
)
model.fit(x_train, y_train)

# Get the trained LassoCV model
lassoCv = model.named_steps['lassocv']

# Print the best alpha
print("Best alpha:", lassoCv.alpha_)

y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

print("\nMAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score: ", r2)


coefficient_table = pd.DataFrame({
    "Feature" : x.columns,
    "Coefficient" : lassoCv.coef_
})

print("\n",coefficient_table)

Best alpha: 0.1

MAE: 0.3104981980822856
MSE: 0.16697027837423398
RMSE: 0.408619968154071
R2 Score:  0.9995440738757985

    Feature  Coefficient
0       SH     4.074742
1      ATT     0.133936
2  ASS_SCR     6.849160
3   STU_ID     5.805057

# Regression Model Comparison Report

## Objective

The objective of this study is to compare the performance of five regression models using the given student performance dataset:

1. Ordinary Least Squares (OLS) Regression
2. Ridge Regression
3. Lasso Regression
4. RidgeCV Regression
5. LassoCV Regression

The models were evaluated using the following performance metrics:

* Mean Absolute Error (MAE)
* Mean Squared Error (MSE)
* Root Mean Squared Error (RMSE)
* R² Score

---

# Model Results

## 1. Ordinary Least Squares (OLS) Regression

### Performance Metrics

| Metric   | Value    |
| -------- | -------- |
| MAE      | 0.310498 |
| MSE      | 0.166970 |
| RMSE     | 0.408620 |
| R² Score | 0.999544 |

### Coefficients

| Feature | Coefficient |
| ------- | ----------- |
| SH      | 1.541476    |
| ATT     | 0.010962    |
| ASS_SCR | 0.475681    |
| STU_ID  | 1.410990    |

---

## 2. Ridge Regression

**Alpha = 1.0**

### Performance Metrics

| Metric   | Value    |
| -------- | -------- |
| MAE      | 0.157363 |
| MSE      | 0.035995 |
| RMSE     | 0.189724 |
| R² Score | 0.999902 |

### Coefficients

| Feature | Coefficient |
| ------- | ----------- |
| SH      | 1.132307    |
| ATT     | 0.016355    |
| ASS_SCR | 0.603667    |
| STU_ID  | 1.227705    |

---

## 3. Lasso Regression

### Performance Metrics

| Metric   | Value    |
| -------- | -------- |
| MAE      | 0.310498 |
| MSE      | 0.166970 |
| RMSE     | 0.408620 |
| R² Score | 0.999544 |

### Coefficients

| Feature | Coefficient |
| ------- | ----------- |
| SH      | 4.074742    |
| ATT     | 0.133936    |
| ASS_SCR | 6.849160    |
| STU_ID  | 5.805057    |

---

## 4. RidgeCV Regression

**Best Alpha = 0.1**

### Performance Metrics

| Metric   | Value    |
| -------- | -------- |
| MAE      | 0.387136 |
| MSE      | 0.249117 |
| RMSE     | 0.499116 |
| R² Score | 0.999320 |

### Coefficients

| Feature | Coefficient |
| ------- | ----------- |
| SH      | 1.489198    |
| ATT     | 0.009709    |
| ASS_SCR | 0.504485    |
| STU_ID  | 1.373094    |

---

## 5. LassoCV Regression

**Best Alpha = 0.1**

### Performance Metrics

| Metric   | Value    |
| -------- | -------- |
| MAE      | 0.310498 |
| MSE      | 0.166970 |
| RMSE     | 0.408620 |
| R² Score | 0.999544 |

### Coefficients

| Feature | Coefficient |
| ------- | ----------- |
| SH      | 4.074742    |
| ATT     | 0.133936    |
| ASS_SCR | 6.849160    |
| STU_ID  | 5.805057    |

---

# Overall Model Comparison

| Model   | Alpha | MAE      | RMSE     | R² Score |
| ------- | ----- | -------- | -------- | -------- |
| OLS     | —     | 0.310498 | 0.408620 | 0.999544 |
| Ridge   | 1.0   | 0.157363 | 0.189724 | 0.999902 |
| Lasso   | 0.1   | 0.310498 | 0.408620 | 0.999544 |
| RidgeCV | 0.1   | 0.387136 | 0.499116 | 0.999320 |
| LassoCV | 0.1   | 0.310498 | 0.408620 | 0.999544 |

---

# Model Ranking

The models were ranked based on higher R² Score and lower error values.

| Rank | Model              | R² Score |
| ---- | ------------------ | -------- |
| 1    | Ridge Regression   | 0.999902 |
| 2    | OLS Regression     | 0.999544 |
| 2    | Lasso Regression   | 0.999544 |
| 2    | LassoCV Regression | 0.999544 |
| 3    | RidgeCV Regression | 0.999320 |

---

# Analysis

* Ridge Regression achieved the highest R² Score and the lowest error values among all models.
* OLS, Lasso, and LassoCV produced nearly identical performance results.
* RidgeCV selected an optimal alpha value automatically; however, its performance was slightly lower than the manually tuned Ridge model.
* All models achieved R² values above 99%, indicating an excellent fit to the dataset.

---

# Conclusion

Based on the experimental results, Ridge Regression is the best-performing model for this dataset.

### Best Model: Ridge Regression

* Alpha = 1.0
* MAE = 0.157363
* MSE = 0.035995
* RMSE = 0.189724
* R² Score = 0.999902

The Ridge model achieved the lowest prediction errors and the highest coefficient of determination (R²), making it the most reliable model for predicting final marks using the selected features.