In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("Data.csv")
dataset = df
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3           38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
dataset.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3           38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [6]:
dataset.tail()

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
dataset.shape

(10, 4)

In [8]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [9]:
dataset.dtypes

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [10]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [11]:
dataset.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [12]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [13]:
dataset.duplicated().sum()

np.int64(0)

In [14]:
dataset
x = dataset.iloc[: , :-1].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       [' ', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
y = dataset.iloc[: , 3].values
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [16]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\samik\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       [' ', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:,0])
print(x)

[[1 44.0 72000.0]
 [3 27.0 48000.0]
 [2 30.0 54000.0]
 [0 38.0 61000.0]
 [2 40.0 63777.77777777778]
 [1 35.0 58000.0]
 [3 38.77777777777778 52000.0]
 [1 48.0 79000.0]
 [2 50.0 83000.0]
 [1 37.0 67000.0]]

In [19]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(),[0])], remainder="passthrough")
x = ct.fit_transform(x)

x.astype(int)

array([[    0,     1,     0,     0,    44, 72000],
       [    0,     0,     0,     1,    27, 48000],
       [    0,     0,     1,     0,    30, 54000],
       [    1,     0,     0,     0,    38, 61000],
       [    0,     0,     1,     0,    40, 63777],
       [    0,     1,     0,     0,    35, 58000],
       [    0,     0,     0,     1,    38, 52000],
       [    0,     1,     0,     0,    48, 79000],
       [    0,     0,     1,     0,    50, 83000],
       [    0,     1,     0,     0,    37, 67000]])

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state = 45)

In [21]:
x_test

array([[0.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [22]:
x_test.astype(int)

array([[    0,     0,     1,     0,    30, 54000],
       [    0,     0,     1,     0,    40, 63777]])

In [23]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [24]:
x_train

array([[-0.37796447, -1.        , -0.37796447,  1.73205081, -1.82709535,
        -1.45240802],
       [-0.37796447, -1.        ,  2.64575131, -0.57735027,  1.47603773,
         1.53784378],
       [-0.37796447,  1.        , -0.37796447, -0.57735027, -0.39095053,
         0.17087153],
       [-0.37796447, -1.        , -0.37796447,  1.73205081, -0.1356359 ,
        -1.11066496],
       [-0.37796447,  1.        , -0.37796447, -0.57735027, -0.6781795 ,
        -0.59805036],
       [-0.37796447,  1.        , -0.37796447, -0.57735027,  1.18880877,
         1.19610072],
       [-0.37796447,  1.        , -0.37796447, -0.57735027,  0.61435084,
         0.59805036],
       [ 2.64575131, -1.        , -0.37796447, -0.57735027, -0.24733605,
        -0.34174306]])